services:
  oot:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    volumes:
      - ./:/oot
    tty: true
    stdin_open: true
